### ISSUE TITLE
missing sensors and data different to what can be tracked using the app 

### ISSUE THREAD

**Issue by Canis089** [natekspencer/hacs-atmo#13]
Hi, first: many thanks, that's the integration I hoped to see for some time.
I was able to install and connect to my Atmo pro, but I am only getting the PM sensors and signal strength, the rest like temperature, humidity, TVOC and pressure are missing. If I compare the PM values to what I can see in the app, I have something between 305 and 50% less of the values shown in the app (no manual calibration done there). The Firmware seems to be up to date, so no idea atm what might be the reason. Maybe you can give me a hint.

**Comment by natekspencer** [comment]
Can you enable debugging and post your logs and some screenshots of both the device in Home Assistant and device/settings in the ATMO app? Also, if I recall correctly, some of the sensors may take a bit to show up, depending on if you are running on battery or plugged in.

**Comment by Canis089** [comment]
I probably only should have waited a bit longer. Now I can see all sensors and the data looks better as well. I think I raised this issue too fast, sorry for that and many thanks again.
Cheerz
Raphael
